name: Build Project

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  remove_files:
    uses: ./.github/workflows/block-reference-eng.yml

  preparation-xml:
    needs: remove_files
    uses: ./.github/workflows/preparation-xml.yml

  convert-xml:
    needs: preparation-xml
    uses: ./.github/workflows/convert-xml.yml