name: Build Project

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  checking-xml:
    uses: ./.github/workflows/remove-references-eng.yml

  preparation-xml:
    needs: checking-xml
    uses: ./.github/workflows/preparation-xml.yml

  convert-xml:
    needs: preparation-xml
    uses: ./.github/workflows/convert-xml.yml