name: Convert XML to DCX

on:
  workflow_call:

jobs:
  convert:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download processed XML files
        uses: actions/download-artifact@v4
        with:
          name: processed-xml-files
          path: ./downloaded_files

      - name: Compile XML files
        run: |
          echo "Processing files from ./downloaded_files"
          dir ./downloaded_files/item-msgbnd
          dir ./downloaded_files/menu-msgbnd

      - name: Delete artifact after use
        run: |
          $artifactId = gh api repos/${{ github.repository }}/actions/artifacts --jq ".artifacts[] | select(.name==\"processed-xml-files\") | .id"
          if ($artifactId) {
            gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifactId
            echo "Artifact deleted"
          } else {
            echo "Artifact not found"
          }
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List all files in repository
        run: |
          Get-ChildItem -Recurse | Select-Object FullName

      - name: Check if directory exists using PowerShell
        run: |
          $path = "item-msgbnd\msg\rusRU\64bit"
          if (Test-Path $path) {
            Write-Host "Directory exists"
          } else {
            Write-Host "Directory does not exist"
            exit 1
          }

      - name: Download Yabber
        run: |
          Invoke-WebRequest -Uri "https://github.com/JKAnderson/Yabber/releases/download/1.3.1/Yabber.1.3.1.zip" -OutFile "Yabber.1.3.1.zip"
          Expand-Archive -Path "Yabber.1.3.1.zip" -DestinationPath "Yabber"

      - name: Convert XML to FMG
        working-directory: item-msgbnd\msg\rusRU\64bit
        run: |
          $xmlFiles = Get-ChildItem -Filter "*.xml"
          foreach ($file in $xmlFiles) {
            Write-Host "Converting: $($file.FullName)"
            Start-Process -FilePath "Yabber/Yabber.exe" -ArgumentList "`"$($file.FullName)`"" -NoNewWindow -Wait
          }

      - name: Remove XML files after conversion
        working-directory: item-msgbnd\msg\rusRU\64bit
        run: |
          Remove-Item -Path "*.xml" -Force

      - name: Upload FMG files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-fmg
          path: "item-msgbnd/msg/rusRU/64bit/*.fmg"

