name: Convert XML to DCX

on:
  workflow_call:

jobs:
  convert:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Yabber
        run: |
          Invoke-WebRequest -Uri "https://github.com/JKAnderson/Yabber/releases/download/1.3.1/Yabber.1.3.1.zip" -OutFile "Yabber.1.3.1.zip"
          Expand-Archive -Path "Yabber.1.3.1.zip" -DestinationPath "Yabber"

      - name: Convert XML to FMG
        run: |
          $xmlFiles = Get-ChildItem -Path "item-msgbnd\msg\rusRU\64bit" -Filter "*.xml"
          foreach ($file in $xmlFiles) {
            Write-Host "Converting: $($file.FullName)"
            Start-Process -FilePath "Yabber/Yabber.exe" -ArgumentList "`"$($file.FullName)`"" -NoNewWindow -Wait
          }

      - name: Remove XML files after conversion
        run: |
          Remove-Item -Path "item-msgbnd\msg\rusRU\64bit\*.xml" -Force
