name: Text Check

on:
    workflow_call:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Завантаження репозиторію
        uses: actions/checkout@v3

      - name: Встановлення залежностей
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-uk
          pip install pandas openpyxl language-tool-python pyspellchecker

      - name: Запуск перевірки тексту
        run: python scripts/check_text.py

      - name: Завантаження звіту як артефакт
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: spellcheck-report
          path: scripts/spellcheck_report.xlsx