name: Text Check

on:
    workflow_call:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Завантаження репозиторію
        uses: actions/checkout@v3

      - name: Встановлення залежностей
        id: install_dependencies
        run: |
          if [ -z "$(ls -A Lang_check 2>/dev/null)" ]; then
            echo "Lang_check порожня. Перевірка не потрібна."
            echo "empty_folder=true" >> $GITHUB_ENV
            exit 0
          fi
          sudo apt-get update
          sudo apt-get install -y aspell aspell-uk
          pip install pandas openpyxl language-tool-python
          python scripts/check_text.py

      - name: Завантаження звіту як артефакт
        uses: actions/upload-artifact@v4
        if: success() && env.empty_folder != 'true'
        with:
          name: spellcheck-report
          path: scripts/spellcheck_report.xlsx
