name: NULLS Check

on:
  workflow_call:

jobs:
  list-xml-ids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract and display XML IDs
        run: |
          while IFS= read -r file; do
            echo "File: $file"
            ids=$(grep -oE '<text id="[0-9]+"[^>]*%null%[^<]*</text>' "$file" | sed -E 's/<text id="([0-9]+)".*/\1/' | sort -n | uniq | tr '\n' ',')
            ids=${ids%,}
            if [ -n "$ids" ]; then
              echo "$ids"
            else
              echo "No IDs found."
            fi
            echo "---------------------"
          done < <(find . -type f -name "*.xml")
