name: Check Unique XML IDs

on:
    workflow_call:

jobs:
  check-xml-ids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Scan XML files for duplicate IDs
        run: |
          ids=$(grep -ohr '<text id="[0-9]\+"' --include "*.xml" . | sed -E 's/<text id="([0-9]+)"/\1/' | sort -n)
          duplicates=$(echo "$ids" | uniq -d)

          if [ -n "$duplicates" ]; then
            echo "Error: Duplicate IDs found in XML files!"
            for id in $duplicates; do
              grep -rn --include="*.xml" "<text id=\"$id\"" .
            done
            exit 1
          else
            echo "All XML IDs are unique."
          fi
